extern const GeoLayout bob_seesaw_platform[];
extern Lights1 seesaw_platform__1_lights;
extern Lights1 seesaw_platform__2_lights;
extern u8 seesaw_platform__1_ci8[];
extern u8 seesaw_platform__1_pal_rgba16[];
extern u8 seesaw_platform__2_ci8[];
extern u8 seesaw_platform__2_pal_rgba16[];
extern Vtx seesaw_platform_000_displaylist_mesh_layer_1_vtx_0[16];
extern Gfx seesaw_platform_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx seesaw_platform_000_displaylist_mesh_layer_1_vtx_1[14];
extern Gfx seesaw_platform_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_seesaw_platform__1[];
extern Gfx mat_revert_seesaw_platform__1[];
extern Gfx mat_seesaw_platform__2[];
extern Gfx mat_revert_seesaw_platform__2[];
extern Gfx seesaw_platform_000_displaylist_mesh_layer_1[];
