extern const GeoLayout bowser_bomb_geo[];
extern Lights1 bomb_Body_lights;
extern Lights1 bomb_Spikes_lights;
extern u8 bomb_koopa_bomb_1_rgba16[];
extern u8 bomb_koopa_bomb_2_rgba16[];
extern Vtx bomb_body_mesh_layer_5_vtx_0[4];
extern Gfx bomb_body_mesh_layer_5_tri_0[];
extern Vtx bomb_spikes_mesh_layer_1_vtx_0[73];
extern Gfx bomb_spikes_mesh_layer_1_tri_0[];
extern Gfx mat_bomb_Body[];
extern Gfx mat_revert_bomb_Body[];
extern Gfx mat_bomb_Spikes[];
extern Gfx bomb_body_mesh_layer_5[];
extern Gfx bomb_spikes_mesh_layer_1[];
