extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const MacroObject bowser_1_area_1_macro_objs[];
extern u8 bowser_1_dl_tile_rgba16[];
extern u8 bowser_1_dl_iwayuka_rgba16[];
extern u8 bowser_1_dl_kabe_rgba16[];
extern Vtx bowser_1_dl_visual_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_1_dl_visual_mesh_layer_1_vtx_0[83];
extern Gfx bowser_1_dl_visual_mesh_layer_1_tri_0[];
extern Vtx bowser_1_dl_visual_mesh_layer_1_vtx_1[64];
extern Gfx bowser_1_dl_visual_mesh_layer_1_tri_1[];
extern Vtx bowser_1_dl_visual_mesh_layer_1_vtx_2[32];
extern Gfx bowser_1_dl_visual_mesh_layer_1_tri_2[];
extern Gfx mat_bowser_1_dl_cloud_wllA_f3d[];
extern Gfx mat_revert_bowser_1_dl_cloud_wllA_f3d[];
extern Gfx mat_bowser_1_dl_kp_rock_f3d[];
extern Gfx mat_revert_bowser_1_dl_kp_rock_f3d[];
extern Gfx mat_bowser_1_dl_kp_rock_side_f3d[];
extern Gfx mat_revert_bowser_1_dl_kp_rock_side_f3d[];
extern Gfx bowser_1_dl_visual_mesh_layer_1[];
