#include "anim_tpose.inc.c"
#include "anim_bowser_stand_up.inc.c"
#include "anim_bowser_walk.inc.c"
#include "anim_bowser_start_walk.inc.c"
#include "anim_bowser_walk_end.inc.c"
#include "anim_bowser_fire_start.inc.c"
