extern const GeoLayout thwomp_switch_opt1[];
extern const GeoLayout thwomp_switch_opt2[];
extern const GeoLayout thwomp_geo[];
extern Lights1 thwomp__1_lights;
extern Lights1 thwomp__2_lights;
extern Lights1 thwomp__3_lights;
extern u8 thwomp_dosune_1_ci8[];
extern u8 thwomp_dosune_1_pal_rgba16[];
extern u8 thwomp_dosune_2_ci8[];
extern u8 thwomp_dosune_2_pal_rgba16[];
extern u8 thwomp_dosune_3_ci8[];
extern u8 thwomp_dosune_3_pal_rgba16[];
extern Vtx thwomp_thwomp_mesh_layer_1_vtx_0[279];
extern Gfx thwomp_thwomp_mesh_layer_1_tri_0[];
extern Gfx mat_thwomp__1[];
extern Gfx mat_revert_thwomp__1[];
extern Gfx mat_thwomp__2[];
extern Gfx mat_revert_thwomp__2[];
extern Gfx mat_thwomp__3[];
extern Gfx mat_revert_thwomp__3[];
extern Gfx thwomp_thwomp_mesh_layer_1[];
extern Gfx thwomp_thwomp_mesh_layer_1_mat_override__2_0[];
extern Gfx thwomp_thwomp_mesh_layer_1_mat_override__3_1[];
