extern const GeoLayout silver_star_geo[];
extern u8 silver_star_silver_body03_ci8[];
extern u8 silver_star_silver_body03_pal_rgba16[];
extern Vtx silver_star_star_mesh_layer_1_vtx_0[43];
extern Gfx silver_star_star_mesh_layer_1_tri_0[];
extern Vtx silver_star_star_mesh_layer_1_vtx_1[26];
extern Gfx silver_star_star_mesh_layer_1_tri_1[];
extern Gfx mat_silver_star_body[];
extern Gfx mat_revert_silver_star_body[];
extern Gfx mat_silver_star_eyes[];
extern Gfx mat_revert_silver_star_eyes[];
extern Gfx silver_star_star_mesh_layer_1[];
