#include "src/game/envfx_snow.h"

const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_4_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_torso_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_player_part_from_parent),
				GEO_ASM(0, geo_player_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 31, 0, 0, luigi_000_offset_torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_neck_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 137, 0, 0, luigi_000_offset_neck_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_player_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_player_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_player_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, luigi_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, -38, -28, -31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, 38, 28, 31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_upperarm_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, 72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_upperarm_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, -72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_player_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_thigh_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, 46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 0, 0, luigi_000_offset_left_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_foot_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, luigi_000_offset_left_foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_thigh_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, -46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 0, 0, luigi_000_offset_right_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_player_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1_mat_override_metal_mat_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_torso_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ASM(0, geo_move_player_part_from_parent),
				GEO_ASM(0, geo_player_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 31, 0, 0, luigi_000_offset_torso_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_neck_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, luigi_000_offset_neck_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_player_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_player_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_player_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_metal_mat_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, -38, -28, -31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_5_mat_override_metal_mat_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, 38, 28, 31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_5_mat_override_metal_mat_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_upperarm_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, 72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1_mat_override_metal_mat_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_forearm_skinned_mesh_layer_1_mat_override_metal_mat_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1_mat_override_metal_mat_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_skinned_mesh_layer_1_mat_override_metal_mat_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_mesh_layer_1_mat_override_metal_mat_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_upperarm_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, -72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1_mat_override_metal_mat_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_forearm_skinned_mesh_layer_1_mat_override_metal_mat_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1_mat_override_metal_mat_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_skinned_mesh_layer_1_mat_override_metal_mat_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_mesh_layer_1_mat_override_metal_mat_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_player_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_thigh_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, 46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_leg_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 0, 0, luigi_000_offset_left_leg_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_foot_skinned_mesh_layer_1_mat_override_metal_mat_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, luigi_000_offset_left_foot_mesh_layer_1_mat_override_metal_mat_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_thigh_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, -46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_leg_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 0, 0, luigi_000_offset_right_leg_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_skinned_mesh_layer_1_mat_override_metal_mat_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_player_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_mat_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1_mat_override_metal_mat_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_torso_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ASM(0, geo_move_player_part_from_parent),
				GEO_ASM(0, geo_player_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 31, 0, 0, luigi_000_offset_torso_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_neck_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 137, 0, 0, luigi_000_offset_neck_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_player_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_player_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_player_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_metal_mat_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, -38, -28, -31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_5_mat_override_metal_mat_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, 38, 28, 31, -118),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_player_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_5_mat_override_metal_mat_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_upperarm_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, 72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1_mat_override_metal_mat_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_forearm_skinned_mesh_layer_1_mat_override_metal_mat_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1_mat_override_metal_mat_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_skinned_mesh_layer_1_mat_override_metal_mat_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_mesh_layer_1_mat_override_metal_mat_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_upperarm_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, -72, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1_mat_override_metal_mat_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_forearm_skinned_mesh_layer_1_mat_override_metal_mat_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1_mat_override_metal_mat_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_skinned_mesh_layer_1_mat_override_metal_mat_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_player_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_player_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_mesh_layer_1_mat_override_metal_mat_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_player_hand_grab_pos),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_thigh_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, 46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_leg_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 0, 0, luigi_000_offset_left_leg_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_left_foot_skinned_mesh_layer_1_mat_override_metal_mat_0),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, luigi_000_offset_left_foot_mesh_layer_1_mat_override_metal_mat_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_thigh_skinned_mesh_layer_1_mat_override_metal_mat_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, -46, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1_mat_override_metal_mat_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_offset_right_leg_skinned_mesh_layer_1_mat_override_metal_mat_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 92, 0, 0, luigi_000_offset_right_leg_mesh_layer_1_mat_override_metal_mat_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_skinned_mesh_layer_1_mat_override_metal_mat_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_player_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_mat_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_4_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 179, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_player_backface_culling),
				GEO_ASM(0, geo_mirror_player_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_player_cap_effect),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_torso_skinned_mesh_layer_1),
								GEO_ASM(0, geo_move_player_part_from_parent),
								GEO_ASM(0, geo_player_tilt_torso),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 31, 0, 0, luigi_000_offset_torso_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_neck_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 137, 0, 0, luigi_000_offset_neck_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_player_head_rotation),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_player_cap_on_off),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_player_eyes),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
															GEO_BRANCH(1, luigi_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, -38, -28, -31, -118),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_player_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 112, -46, 38, 28, 31, -118),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_player_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_upperarm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, 72, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_forearm_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_player_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_player_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_upperarm_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 94, -1, -72, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_forearm_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_player_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_player_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_player_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_thigh_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, 46, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_leg_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 0, 0, luigi_000_offset_left_leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_left_foot_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, luigi_000_offset_left_foot_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_thigh_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 10, -46, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_offset_right_leg_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 92, 0, 0, luigi_000_offset_right_leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_player_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, luigi_001_switch_opt1),
					GEO_BRANCH(1, luigi_001_switch_opt2),
					GEO_BRANCH(1, luigi_001_switch_opt3),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_player_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
