extern const GeoLayout cap_box_switch_node_opt1[];
extern const GeoLayout cap_box_switch_node_opt2[];
extern const GeoLayout cap_box_switch_node_opt3[];
extern const GeoLayout cap_box_switch_node_opt4[];
extern const GeoLayout cap_box_geo[];
extern Lights1 cap_box_wing_lights;
extern Lights1 cap_box_metal_lights;
extern Lights1 cap_box_vanish_lights;
extern Lights1 cap_box_normal_lights;
extern Lights1 cap_box_question_lights;
extern u8 cap_box_wing_ci8[];
extern u8 cap_box_wing_pal_rgba16[];
extern u8 cap_box_metal_ci8[];
extern u8 cap_box_metal_pal_rgba16[];
extern u8 cap_box_vanish_ci8[];
extern u8 cap_box_vanish_pal_rgba16[];
extern u8 cap_box_regular_ci8[];
extern u8 cap_box_regular_pal_rgba16[];
extern u8 cap_box_question_ci4[];
extern u8 cap_box_question_pal_rgba16[];
extern Vtx cap_box_displaylist_mesh_layer_1_vtx_0[24];
extern Gfx cap_box_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_cap_box_wing[];
extern Gfx mat_revert_cap_box_wing[];
extern Gfx mat_cap_box_metal[];
extern Gfx mat_revert_cap_box_metal[];
extern Gfx mat_cap_box_vanish[];
extern Gfx mat_revert_cap_box_vanish[];
extern Gfx mat_cap_box_normal[];
extern Gfx mat_revert_cap_box_normal[];
extern Gfx mat_cap_box_question[];
extern Gfx mat_revert_cap_box_question[];
extern Gfx cap_box_displaylist_mesh_layer_1[];
extern Gfx cap_box_displaylist_mesh_layer_1_mat_override_metal_0[];
extern Gfx cap_box_displaylist_mesh_layer_1_mat_override_vanish_1[];
extern Gfx cap_box_displaylist_mesh_layer_1_mat_override_normal_2[];
extern Gfx cap_box_displaylist_mesh_layer_1_mat_override_question_3[];