extern const GeoLayout power_flower_power_flower_open[];
extern const GeoLayout power_flower_geo[];
extern Lights1 power_flower_power_flower_body_lights;
extern Lights1 power_flower_power_flower_petals_lights;
extern u8 power_flower_power_flower_1_ci8[];
extern u8 power_flower_power_flower_1_pal_rgba16[];
extern u8 power_flower_power_flower_2_rgba16[];
extern Vtx power_flower_displaylist_mesh_layer_1_vtx_0[72];
extern Gfx power_flower_displaylist_mesh_layer_1_tri_0[];
extern Vtx power_flower_displaylist_mesh_layer_4_vtx_0[15];
extern Gfx power_flower_displaylist_mesh_layer_4_tri_0[];
extern Vtx power_flower_switch_option_displaylist_mesh_layer_1_vtx_0[104];
extern Gfx power_flower_switch_option_displaylist_mesh_layer_1_tri_0[];
extern Vtx power_flower_switch_option_displaylist_mesh_layer_4_vtx_0[37];
extern Gfx power_flower_switch_option_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_power_flower_power_flower_body[];
extern Gfx mat_revert_power_flower_power_flower_body[];
extern Gfx mat_power_flower_power_flower_petals[];
extern Gfx mat_revert_power_flower_power_flower_petals[];
extern Gfx power_flower_displaylist_mesh_layer_1[];
extern Gfx power_flower_displaylist_mesh_layer_4[];
extern Gfx power_flower_switch_option_displaylist_mesh_layer_1[];
extern Gfx power_flower_switch_option_displaylist_mesh_layer_4[];
