extern const GeoLayout geo_bitdw_000600[];
extern u8 collapsing_stairs_5_itimatu_rgba16[];
extern u8 collapsing_stairs_5_yuka_rgba16[];
extern Vtx collapsing_stairs_5_000_displaylist_mesh_layer_1_vtx_0[16];
extern Gfx collapsing_stairs_5_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx collapsing_stairs_5_000_displaylist_mesh_layer_1_vtx_1[4];
extern Gfx collapsing_stairs_5_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_collapsing_stairs_5_mat_yuka5_f3d[];
extern Gfx mat_revert_collapsing_stairs_5_mat_yuka5_f3d[];
extern Gfx mat_collapsing_stairs_5_mat_yuka_ue_f3d[];
extern Gfx mat_revert_collapsing_stairs_5_mat_yuka_ue_f3d[];
extern Gfx collapsing_stairs_5_000_displaylist_mesh_layer_1[];
