extern const GeoLayout wf_sliding_platform_geo[];
extern u8 sliding_platform_n_bldtex01_rgba16[];
extern u8 sliding_platform_n_renga05_rgba16[];
extern Vtx sliding_platform_wf_sliding_platform_mesh_layer_1_vtx_0[4];
extern Gfx sliding_platform_wf_sliding_platform_mesh_layer_1_tri_0[];
extern Vtx sliding_platform_wf_sliding_platform_mesh_layer_1_vtx_1[8];
extern Gfx sliding_platform_wf_sliding_platform_mesh_layer_1_tri_1[];
extern Gfx mat_sliding_platform_bldtex01_f3d_002[];
extern Gfx mat_revert_sliding_platform_bldtex01_f3d_002[];
extern Gfx mat_sliding_platform_renga05_f3d_002[];
extern Gfx mat_revert_sliding_platform_renga05_f3d_002[];
extern Gfx sliding_platform_wf_sliding_platform_mesh_layer_1[];
