#include "src/game/envfx_snow.h"

const GeoLayout king_bobomb_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 128, 300),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 192, 0, king_bobomb_kbob_arm_l_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_kbob_hand_l_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 157, 0, 0, king_bobomb_kbob_hand_l_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 192, 0, king_bobomb_kbob_arm_r_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_kbob_hand_r_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -157, 0, 0, king_bobomb_kbob_hand_r_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_update_held_player_pos),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 192, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_FORCE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, king_bobomb_kbob_body_dlist_mesh_layer_5),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, -192, 0, king_bobomb_kbob_eye_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_kbob_crown_mesh_layer_4),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 56, -80, 0, 0, 92, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_kbob_leg_l_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_kbob_foot_l_skinned_mesh_layer_4),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -40, 5, 0, 178, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_kbob_foot_l_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -56, -80, 0, 0, 88, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_kbob_leg_r_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, king_bobomb_kbob_foot_r_skinned_mesh_layer_4),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -40, -5, 0, -178, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, king_bobomb_kbob_foot_r_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, -192, 0, king_bobomb_kbob_mustach_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
